apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.nginx.name }}
spec:
  selector:
    app: nginx
  type: {{ .Values.service.nginx.type }}
  ports:
  - port: {{ .Values.service.nginx.port }}
    targetPort: {{ .Values.service.nginx.targetPort }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.apache.name }}
spec:
  selector:
    app: apache
  type: {{ .Values.service.apache.type }}
  ports:
  - port: {{ .Values.service.apache.port }}
    targetPort: {{ .Values.service.apache.targetPort }}