replicaCount: 1

image:
  apache:
    repository: ahineia/apache-ci-cd
    tag: "{{ .Values.apache.imageTag }}"
    pullPolicy: IfNotPresent
    containerPort: 8080
  nginx:
    repository: ahineia/nginx-ci-cd
    tag: "{{ .Values.nginx.imageTag }}"
    pullPolicy: IfNotPresent
    containerPort: 80

service:
  nginx:
    name: nginx-service
    type: NodePort
    port: 80
    targetPort: 80
  apache:
    name: apache-service
    type: NodePort
    port: 8080
    targetPort: 8080
