replicaCount: 1

image:
  apache:
    repository: ahineia/apache-ci-cd
    tag: 97153365deb24b6e2176f887bc9c50321590d6e4
    pullPolicy: IfNotPresent
    containerPort: 8080
  nginx:
    repository: ahineia/nginx-ci-cd
    tag: 97153365deb24b6e2176f887bc9c50321590d6e4
    pullPolicy: IfNotPresent
    containerPort: 80

service:
  nginx:
    name: nginx-service
    type: ClusterIP
    port: 80
    targetPort: 80
  apache:
    name: apache-service
    type: ClusterIP
    port: 8080
    targetPort: 8080

ingress:
  name: nginx-ingress31
  className: nginx
