apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: "git@github.com:RomerooIT/argocd.git"
    targetRevision: HEAD
    path: "helm-charts/nginx-app"
    helm:
      valueFiles:
      - values.yaml
      parameters:
      - name: "container.image"
        value: stable-alpine3.17-slim

  destination:
    server: https://kubernetes.default.svc
    namespace: task31

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true