FROM nginx:1.25.4

RUN rm /etc/nginx/conf.d/default.conf

WORKDIR /etc/nginx/conf.d
COPY anotherconfig.conf .

RUN sed -i '6 a\load_module modules/ngx_http_image_filter_module.so;' /etc/nginx/nginx.conf

WORKDIR /var/www
COPY www/. .

WORKDIR /etc/letsencrypt
COPY letsencrypt/. .

RUN touch /var/run/nginx.pid && \
    chown nginx:nginx /var/run/nginx.pid && \
    chown -R nginx:nginx /etc/nginx /var/www  /var/cache/nginx /etc/letsencrypt
