name: Build and Publish Docker Images
on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Show directory contents and path
        run: |
          ls -la
          pwd

      - name: Build and push Nginx Docker image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          IMAGE_TAG: 1.0.${{ github.run_number }}
        working-directory: /home/runner/work/argocd/argocd/MyApp/Nginx-Docker
        run: |
          docker build -t ahineia/nginx-ci-cd:${IMAGE_TAG} .
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker push ahineia/nginx-ci-cd:${IMAGE_TAG}

      - name: Build and push Apache Docker image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          IMAGE_TAG: 1.0.${{ github.run_number }}
          GH_TOKEN: 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
        working-directory: /home/runner/work/argocd/argocd/MyApp/Apache-Docker
        run: |
          docker build -t ahineia/apache-ci-cd:${IMAGE_TAG} .
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker push ahineia/apache-ci-cd:${IMAGE_TAG}

      - name: Update values.yaml
        env:
          IMAGE_TAG: 1.0.${{ github.run_number }}
        working-directory: /home/runner/work/argocd/argocd/helm-charts/nginx-app
        run: |
          echo "Replacing image tag in values.yaml"
          sed -i "s/tag: \".*\"/tag: \"${IMAGE_TAG}\"/" values.yaml

          echo "Setting git user name"
          git config --global user.name "RomerooIT"

          echo "Setting git user email"
          git config --global user.email "roman.knyrko@mail.ru"

          echo "Adding values.yaml to git"
          git add values.yaml

          git status

          echo "Committing changes"
          git commit -m "Update image tag to ${IMAGE_TAG}"

          echo "Pushing changes to remote repository"
          git push --token $GH_TOKEN
