name: Build and Publish Docker Images
on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Show directory contents and path
        run: |
          ls -la
          pwd

      - name: Build and push Nginx Docker image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          IMAGE_TAG: 1.0.${{ github.run_number }}
        working-directory: /home/runner/work/argocd/argocd/MyApp/Nginx-Docker
        run: |
          docker build -t ahineia/nginx-ci-cd:${IMAGE_TAG} .
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker push ahineia/nginx-ci-cd:${IMAGE_TAG}

      - name: Build and push Apache Docker image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          IMAGE_TAG: 1.0.${{ github.run_number }}
        working-directory: /home/runner/work/argocd/argocd/MyApp/Apache-Docker
        run: |
          docker build -t ahineia/apache-ci-cd:${IMAGE_TAG} .
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker push ahineia/apache-ci-cd:${IMAGE_TAG}

      - name: Update values.yaml
        env:
          IMAGE_TAG: 1.0.${{ github.run_number }}
        working-directory: /home/runner/work/argocd/argocd/helm-charts/nginx-app
        run: |
          echo "Replacing image tag in values.yaml"
          sed -i "s/tag: \".*\"/tag: \"${IMAGE_TAG}\"/" values.yaml


      - name: GIT commit and push docs
        env: 
          CI_COMMIT_MESSAGE: Changed docker images tags
          CI_COMMIT_AUTHOR: RomerooIT
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "roman.knyrko@mail.ru"
          git add .
          git commit -m "${{ env.CI_COMMIT_MESSAGE }}"
          git push "https://${ACCESS_TOKEN}@github.com/RomerooIT/argocd.git" main
