name: Build and Publish Docker Images
on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Show directory contents and path
        run: |
          ls -la
          pwd

      - name: Build and push Nginx Docker image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          IMAGE_TAG: ${{ github.sha }}
          SHORT_SHA: ${{ github.sha[0:7] }} # Укороченный тег
        working-directory: ./MyApp/NginxDocker
        run: |
          docker build -t ahineia/nginx-ci-cd:${SHORT_SHA} .
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker push ahineia/nginx-ci-cd:${SHORT_SHA}

      - name: Build and push Apache Docker image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          IMAGE_TAG: ${{ github.sha }}
          SHORT_SHA: ${{ github.sha[0:7] }} # Укороченный тег
        working-directory: ./MyApp/Apache-Docker
        run: |
          docker build -t ahineia/apache-ci-cd:${SHORT_SHA} .
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker push ahineia/apache-ci-cd:${SHORT_SHA}
