name: Build and Publish Docker Images
on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Show directory contents and path
        run: |
          ls -la
          pwd

      - name: Set tag and save as artifact
        id: set_tag
        run: |
          echo "::set-output name=tag::${{ github.sha }}"
          echo "${{ github.sha }}" > tag.txt
        # Save tag.txt as an artifact
      - name: Save tag artifact
        uses: actions/upload-artifact@v2
        with:
          name: tag-artifact
          path: tag.txt

      - name: Build and push Nginx Docker image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        working-directory: /home/runner/work/argocd/argocd/MyApp/Nginx-Docker
        run: |
          # Retrieve the tag from the artifact
          cat ${{ runner.workspace }}/tag-artifact/tag.txt > tag.txt
          IMAGE_TAG=$(cat tag.txt)
          docker build -t ahineia/nginx-ci-cd:${IMAGE_TAG} .
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker push ahineia/nginx-ci-cd:${IMAGE_TAG}

      - name: Build and push Apache Docker image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        working-directory: /home/runner/work/argocd/argocd/MyApp/Apache-Docker
        run: |
          # Retrieve the tag from the artifact
          cat ${{ runner.workspace }}/tag-artifact/tag.txt > tag.txt
          IMAGE_TAG=$(cat tag.txt)
          docker build -t ahineia/apache-ci-cd:${IMAGE_TAG} .
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker push ahineia/apache-ci-cd:${IMAGE_TAG}
